server:
  port: 8080


spring:
  datasource:
    url: jdbc:mysql://27.50.142.211:63306/jimisun?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: dsdb@1
    driver-class-name: com.mysql.cj.jdbc.Driver

