/*
 Navicat Premium Data Transfer

 Source Server         : 得实Mysql
 Source Server Type    : MySQL
 Source Server Version : 50721
 Source Host           : 27.50.142.211:63306
 Source Schema         : jimisun

 Target Server Type    : MySQL
 Target Server Version : 50721
 File Encoding         : 65001

 Date: 01/03/2022 22:53:27
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for process
-- ----------------------------
DROP TABLE IF EXISTS `process`;
CREATE TABLE `process` (
  `process_id` varchar(255) COLLATE utf8mb4_bin NOT NULL COMMENT '流程实例ID',
  `process_template_key` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '流程模板KEY',
  `process_bus_key` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '流程业务KEY',
  `process_bus_data` longtext COLLATE utf8mb4_bin COMMENT '流程业务数据',
  `process_attribute_data` longtext COLLATE utf8mb4_bin COMMENT '流程属性数据',
  `process_status` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '流程实例状态',
  `process_open_time` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '流程实例开始时间',
  `process_close_time` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '流程实例结束时间',
  PRIMARY KEY (`process_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

-- ----------------------------
-- Records of process
-- ----------------------------
BEGIN;
COMMIT;

-- ----------------------------
-- Table structure for process_task
-- ----------------------------
DROP TABLE IF EXISTS `process_task`;
CREATE TABLE `process_task` (
  `process_task_id` varchar(255) COLLATE utf8mb4_bin NOT NULL COMMENT '流程任务ID',
  `process_node_key` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '流程节点KEY',
  `process_node_name` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '流程节点名称',
  `process_id` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '流程实例ID',
  `process_template_key` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '流程模板KEY',
  `process_task_actor` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '流程任务执行者',
  `process_task_operation` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '流程任务实际执行人',
  `process_task_form_url` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '流程任务表单地址',
  `process_bus_data_snapshot` longtext COLLATE utf8mb4_bin COMMENT '流程业务数据快照',
  `process_task_opinion` longtext COLLATE utf8mb4_bin COMMENT '流程任务意见',
  `process_task_node_type` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '流程任务类型',
  `process_task_status` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '流程任务状态',
  `process_task_create_time` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '流程任务创建时间',
  `process_task_close_time` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '流程任务结束时间',
  `process_task_remark` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '流程任务注释',
  PRIMARY KEY (`process_task_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

-- ----------------------------
-- Records of process_task
-- ----------------------------
BEGIN;
INSERT INTO `process_task` (`process_task_id`, `process_node_key`, `process_node_name`, `process_id`, `process_template_key`, `process_task_actor`, `process_task_operation`, `process_task_form_url`, `process_bus_data_snapshot`, `process_task_opinion`, `process_task_node_type`, `process_task_status`, `process_task_create_time`, `process_task_close_time`, `process_task_remark`) VALUES ('05f3a75a3c1a4a4289889fdcdcee13f1', 'start', '网络策略申请开始节点', 'b4e40b4e543f43a39c5241b34f2c5a19', 'wlclsq', '超级管理员', '超级管理员', '', NULL, '', 'start', 'treated', '2022/03/01 22:03:32', '2022/03/01 22:03:32', '流程引擎跳过开始节点');
INSERT INTO `process_task` (`process_task_id`, `process_node_key`, `process_node_name`, `process_id`, `process_template_key`, `process_task_actor`, `process_task_operation`, `process_task_form_url`, `process_bus_data_snapshot`, `process_task_opinion`, `process_task_node_type`, `process_task_status`, `process_task_create_time`, `process_task_close_time`, `process_task_remark`) VALUES ('062cf98a036148cab0541daff58a768b', 'wlclsq_dsjjsh', '网络策略申请_大数据审核', 'fb1c5f32b4794d8aa93a29e2418947f5', 'wlclsq', 'dsjzx', 'jimisun', NULL, NULL, '意见', 'branch_task', 'treated', '2022/03/01 22:45:54', '2022/03/01 22:46:36', NULL);
INSERT INTO `process_task` (`process_task_id`, `process_node_key`, `process_node_name`, `process_id`, `process_template_key`, `process_task_actor`, `process_task_operation`, `process_task_form_url`, `process_bus_data_snapshot`, `process_task_opinion`, `process_task_node_type`, `process_task_status`, `process_task_create_time`, `process_task_close_time`, `process_task_remark`) VALUES ('0dc680918cd143148f9db2f4eaddc6a9', 'wlclsq_yyscl', '网络策略申请_运营商处理', 'fb1c5f32b4794d8aa93a29e2418947f5', 'wlclsq', 'zhongyuanyun', '超级管理员', NULL, NULL, NULL, 'branch_task', 'cancel', '2022/03/01 22:36:47', NULL, NULL);
INSERT INTO `process_task` (`process_task_id`, `process_node_key`, `process_node_name`, `process_id`, `process_template_key`, `process_task_actor`, `process_task_operation`, `process_task_form_url`, `process_bus_data_snapshot`, `process_task_opinion`, `process_task_node_type`, `process_task_status`, `process_task_create_time`, `process_task_close_time`, `process_task_remark`) VALUES ('0ecc65e267fe48258be3c369c55f66d0', 'wlclsq_zssh', '网络策略申请_正数审核', '70c4cfe0913048dabaad5671182295da', 'wlclsq', 'dsjj', 'jimisun', NULL, NULL, '意见', 'branch_task', 'treated', '2022/03/01 22:31:45', '2022/03/01 22:32:22', NULL);
INSERT INTO `process_task` (`process_task_id`, `process_node_key`, `process_node_name`, `process_id`, `process_template_key`, `process_task_actor`, `process_task_operation`, `process_task_form_url`, `process_bus_data_snapshot`, `process_task_opinion`, `process_task_node_type`, `process_task_status`, `process_task_create_time`, `process_task_close_time`, `process_task_remark`) VALUES ('1432a633b2b242eda21204e069bb0fd5', 'start', '网络策略申请开始节点', 'fb1c5f32b4794d8aa93a29e2418947f5', 'wlclsq', '超级管理员', '超级管理员', '', NULL, '', 'start', 'treated', '2022/03/01 22:36:21', '2022/03/01 22:36:21', '流程引擎跳过开始节点');
INSERT INTO `process_task` (`process_task_id`, `process_node_key`, `process_node_name`, `process_id`, `process_template_key`, `process_task_actor`, `process_task_operation`, `process_task_form_url`, `process_bus_data_snapshot`, `process_task_opinion`, `process_task_node_type`, `process_task_status`, `process_task_create_time`, `process_task_close_time`, `process_task_remark`) VALUES ('16b520e2818c4971ac0b868b1b839f8e', 'wlclsq_zssh', '网络策略申请_正数审核', 'fb1c5f32b4794d8aa93a29e2418947f5', 'wlclsq', 'dsjj', 'jimisun', NULL, NULL, '意见', 'branch_task', 'treated', '2022/03/01 22:46:37', '2022/03/01 22:46:51', NULL);
INSERT INTO `process_task` (`process_task_id`, `process_node_key`, `process_node_name`, `process_id`, `process_template_key`, `process_task_actor`, `process_task_operation`, `process_task_form_url`, `process_bus_data_snapshot`, `process_task_opinion`, `process_task_node_type`, `process_task_status`, `process_task_create_time`, `process_task_close_time`, `process_task_remark`) VALUES ('1f7469f3d3fb42e5b980f337bafa1cb8', 'wlclsq_dsjjsh', '网络策略申请_大数据审核', 'd6dba4914e0e494281db6dd35e22208c', 'wlclsq', 'dsjj', 'jimisun', NULL, NULL, '意见', 'branch_task', 'treated', '2022/03/01 22:08:59', '2022/03/01 22:09:28', NULL);
INSERT INTO `process_task` (`process_task_id`, `process_node_key`, `process_node_name`, `process_id`, `process_template_key`, `process_task_actor`, `process_task_operation`, `process_task_form_url`, `process_bus_data_snapshot`, `process_task_opinion`, `process_task_node_type`, `process_task_status`, `process_task_create_time`, `process_task_close_time`, `process_task_remark`) VALUES ('241e6b12198140b9bbe5eee911dd3d06', 'wlclsq_tjsq', '网络策略申请_厅局申请', 'fb1c5f32b4794d8aa93a29e2418947f5', 'wlclsq', 'shuiliju', 'jimisun', NULL, NULL, '意见', 'task', 'treated', '2022/03/01 22:36:21', '2022/03/01 22:36:45', NULL);
INSERT INTO `process_task` (`process_task_id`, `process_node_key`, `process_node_name`, `process_id`, `process_template_key`, `process_task_actor`, `process_task_operation`, `process_task_form_url`, `process_bus_data_snapshot`, `process_task_opinion`, `process_task_node_type`, `process_task_status`, `process_task_create_time`, `process_task_close_time`, `process_task_remark`) VALUES ('258e69a883af438eabafea53cbec1069', 'wlclsq_hzsjjg', '网络策略申请_汇总数据结果', 'fb1c5f32b4794d8aa93a29e2418947f5', 'wlclsq', '超级管理员', '超级管理员', '', NULL, '', 'close_gateway', 'treated', '2022/03/01 22:51:24', '2022/03/01 22:51:24', '流程引擎跳过结束网关');
INSERT INTO `process_task` (`process_task_id`, `process_node_key`, `process_node_name`, `process_id`, `process_template_key`, `process_task_actor`, `process_task_operation`, `process_task_form_url`, `process_bus_data_snapshot`, `process_task_opinion`, `process_task_node_type`, `process_task_status`, `process_task_create_time`, `process_task_close_time`, `process_task_remark`) VALUES ('2b5049eeaf184c8db6407c646f99fb58', 'wlclsq_dsjjsh', '网络策略申请_大数据审核', 'fb1c5f32b4794d8aa93a29e2418947f5', 'wlclsq', 'dsjzx', 'jimisun', NULL, NULL, '意见', 'branch_task', 'treated', '2022/03/01 22:36:47', '2022/03/01 22:37:09', NULL);
INSERT INTO `process_task` (`process_task_id`, `process_node_key`, `process_node_name`, `process_id`, `process_template_key`, `process_task_actor`, `process_task_operation`, `process_task_form_url`, `process_bus_data_snapshot`, `process_task_opinion`, `process_task_node_type`, `process_task_status`, `process_task_create_time`, `process_task_close_time`, `process_task_remark`) VALUES ('3d1a20d2762948c3a34c83ed9657a074', 'wlclsq_yyscl', '网络策略申请_运营商处理', 'fb1c5f32b4794d8aa93a29e2418947f5', 'wlclsq', 'laintong', 'jimisun', NULL, NULL, '意见', 'branch_task', 'treated', '2022/03/01 22:36:48', '2022/03/01 22:51:22', NULL);
INSERT INTO `process_task` (`process_task_id`, `process_node_key`, `process_node_name`, `process_id`, `process_template_key`, `process_task_actor`, `process_task_operation`, `process_task_form_url`, `process_bus_data_snapshot`, `process_task_opinion`, `process_task_node_type`, `process_task_status`, `process_task_create_time`, `process_task_close_time`, `process_task_remark`) VALUES ('3dd74108b2644627905ed492fc4f429b', 'wlclsq_hzsjjg', '网络策略申请_汇总数据结果', 'b4e40b4e543f43a39c5241b34f2c5a19', 'wlclsq', '超级管理员', '超级管理员', '', NULL, '', 'close_gateway', 'treated', '2022/03/01 22:06:45', '2022/03/01 22:06:45', '流程引擎跳过结束网关');
INSERT INTO `process_task` (`process_task_id`, `process_node_key`, `process_node_name`, `process_id`, `process_template_key`, `process_task_actor`, `process_task_operation`, `process_task_form_url`, `process_bus_data_snapshot`, `process_task_opinion`, `process_task_node_type`, `process_task_status`, `process_task_create_time`, `process_task_close_time`, `process_task_remark`) VALUES ('4232f5bd9cfd47319c67f61135290927', 'wlclsq_tjsq', '网络策略申请_厅局申请', '5e9a858311f0456db66eca9e94db9222', 'wlclsq', 'linyeju', NULL, NULL, NULL, NULL, 'task', 'untreated', '2022/03/01 21:29:09', NULL, NULL);
INSERT INTO `process_task` (`process_task_id`, `process_node_key`, `process_node_name`, `process_id`, `process_template_key`, `process_task_actor`, `process_task_operation`, `process_task_form_url`, `process_bus_data_snapshot`, `process_task_opinion`, `process_task_node_type`, `process_task_status`, `process_task_create_time`, `process_task_close_time`, `process_task_remark`) VALUES ('4bc5f7233a284a9cb56b637d7b2d271f', 'start', '网络策略申请开始节点', 'd6dba4914e0e494281db6dd35e22208c', 'wlclsq', '超级管理员', '超级管理员', '', NULL, '', 'start', 'treated', '2022/03/01 22:08:42', '2022/03/01 22:08:42', '流程引擎跳过开始节点');
INSERT INTO `process_task` (`process_task_id`, `process_node_key`, `process_node_name`, `process_id`, `process_template_key`, `process_task_actor`, `process_task_operation`, `process_task_form_url`, `process_bus_data_snapshot`, `process_task_opinion`, `process_task_node_type`, `process_task_status`, `process_task_create_time`, `process_task_close_time`, `process_task_remark`) VALUES ('4eef78bde0a94059906fd35ee0722132', 'wlclsq_hzsjjg', '网络策略申请_汇总数据结果', '8cdef1c18bf842799be7b266597d7ca0', 'wlclsq', '超级管理员', '超级管理员', '', NULL, '', 'close_gateway', 'treated', '2022/03/01 21:58:43', '2022/03/01 21:58:43', '流程引擎跳过结束网关');
INSERT INTO `process_task` (`process_task_id`, `process_node_key`, `process_node_name`, `process_id`, `process_template_key`, `process_task_actor`, `process_task_operation`, `process_task_form_url`, `process_bus_data_snapshot`, `process_task_opinion`, `process_task_node_type`, `process_task_status`, `process_task_create_time`, `process_task_close_time`, `process_task_remark`) VALUES ('529aa5e5c2b34e32a71f531d33aa30c9', 'wlclsq_yyscl', '网络策略申请_运营商处理', 'b4e40b4e543f43a39c5241b34f2c5a19', 'wlclsq', 'zhongyuanyun', 'jimisun', NULL, NULL, '意见', 'branch_task', 'treated', '2022/03/01 22:04:56', '2022/03/01 22:05:43', NULL);
INSERT INTO `process_task` (`process_task_id`, `process_node_key`, `process_node_name`, `process_id`, `process_template_key`, `process_task_actor`, `process_task_operation`, `process_task_form_url`, `process_bus_data_snapshot`, `process_task_opinion`, `process_task_node_type`, `process_task_status`, `process_task_create_time`, `process_task_close_time`, `process_task_remark`) VALUES ('52ce6ac487b54554a0788ca586e3efff', 'wlclsq_dsjjsh', '网络策略申请_大数据审核', 'b4e40b4e543f43a39c5241b34f2c5a19', 'wlclsq', 'dsjj', 'jimisun', NULL, NULL, '意见', 'branch_task', 'treated', '2022/03/01 22:04:55', '2022/03/01 22:05:35', NULL);
INSERT INTO `process_task` (`process_task_id`, `process_node_key`, `process_node_name`, `process_id`, `process_template_key`, `process_task_actor`, `process_task_operation`, `process_task_form_url`, `process_bus_data_snapshot`, `process_task_opinion`, `process_task_node_type`, `process_task_status`, `process_task_create_time`, `process_task_close_time`, `process_task_remark`) VALUES ('5e73492c25f342078d6cb3787a1c95fe', 'wlclsq_zssh', '网络策略申请_正数审核', 'b4e40b4e543f43a39c5241b34f2c5a19', 'wlclsq', 'dsjj', 'jimisun', NULL, NULL, '意见', 'branch_task', 'treated', '2022/03/01 22:06:07', '2022/03/01 22:06:25', NULL);
INSERT INTO `process_task` (`process_task_id`, `process_node_key`, `process_node_name`, `process_id`, `process_template_key`, `process_task_actor`, `process_task_operation`, `process_task_form_url`, `process_bus_data_snapshot`, `process_task_opinion`, `process_task_node_type`, `process_task_status`, `process_task_create_time`, `process_task_close_time`, `process_task_remark`) VALUES ('6d2b2ca4cbe84127a46a74b9b813a7e8', 'wlclsq_dsjjsh', '网络策略申请_大数据审核', '70c4cfe0913048dabaad5671182295da', 'wlclsq', 'dsjzx', 'jimisun', NULL, NULL, '意见', 'branch_task', 'treated', '2022/03/01 22:28:20', '2022/03/01 22:31:44', NULL);
INSERT INTO `process_task` (`process_task_id`, `process_node_key`, `process_node_name`, `process_id`, `process_template_key`, `process_task_actor`, `process_task_operation`, `process_task_form_url`, `process_bus_data_snapshot`, `process_task_opinion`, `process_task_node_type`, `process_task_status`, `process_task_create_time`, `process_task_close_time`, `process_task_remark`) VALUES ('6daef3d54c6f46779a3aabdc5fce81e9', 'wlclsq_yyscl', '网络策略申请_运营商处理', '70c4cfe0913048dabaad5671182295da', 'wlclsq', 'zhongyuanyun', 'jimisun', NULL, NULL, '意见', 'branch_task', 'treated', '2022/03/01 22:28:20', '2022/03/01 22:31:19', NULL);
INSERT INTO `process_task` (`process_task_id`, `process_node_key`, `process_node_name`, `process_id`, `process_template_key`, `process_task_actor`, `process_task_operation`, `process_task_form_url`, `process_bus_data_snapshot`, `process_task_opinion`, `process_task_node_type`, `process_task_status`, `process_task_create_time`, `process_task_close_time`, `process_task_remark`) VALUES ('77cc057df3b8458b9ec407f9324dff49', 'wlclsq_tjsq', '网络策略申请_厅局申请', '70c4cfe0913048dabaad5671182295da', 'wlclsq', 'linyeju', '超级管理员', NULL, NULL, NULL, 'task', 'cancel', '2022/03/01 22:27:36', NULL, NULL);
INSERT INTO `process_task` (`process_task_id`, `process_node_key`, `process_node_name`, `process_id`, `process_template_key`, `process_task_actor`, `process_task_operation`, `process_task_form_url`, `process_bus_data_snapshot`, `process_task_opinion`, `process_task_node_type`, `process_task_status`, `process_task_create_time`, `process_task_close_time`, `process_task_remark`) VALUES ('7c7a0d1f5dc7462bb56c4a909e8af4bb', 'wlclsq_end', '网络策略申请_结束节点', 'fb1c5f32b4794d8aa93a29e2418947f5', 'wlclsq', '超级管理员', '超级管理员', '', NULL, '', 'end', 'treated', '2022/03/01 22:51:25', '2022/03/01 22:51:25', '流程引擎自动执行结束节点');
INSERT INTO `process_task` (`process_task_id`, `process_node_key`, `process_node_name`, `process_id`, `process_template_key`, `process_task_actor`, `process_task_operation`, `process_task_form_url`, `process_bus_data_snapshot`, `process_task_opinion`, `process_task_node_type`, `process_task_status`, `process_task_create_time`, `process_task_close_time`, `process_task_remark`) VALUES ('7d5e3d2926a14e41993cce3f46fc5487', 'wlclsq_hzsjjg', '网络策略申请_汇总数据结果', '70c4cfe0913048dabaad5671182295da', 'wlclsq', '超级管理员', '超级管理员', '', NULL, '', 'close_gateway', 'treated', '2022/03/01 22:32:45', '2022/03/01 22:32:45', '流程引擎跳过结束网关');
INSERT INTO `process_task` (`process_task_id`, `process_node_key`, `process_node_name`, `process_id`, `process_template_key`, `process_task_actor`, `process_task_operation`, `process_task_form_url`, `process_bus_data_snapshot`, `process_task_opinion`, `process_task_node_type`, `process_task_status`, `process_task_create_time`, `process_task_close_time`, `process_task_remark`) VALUES ('864bafe6dd9343e4a34c5bd2d2938683', 'wlclsq_dsjjsh', '网络策略申请_大数据审核', 'd6dba4914e0e494281db6dd35e22208c', 'wlclsq', 'dsjzx', '超级管理员', NULL, NULL, NULL, 'branch_task', 'cancel', '2022/03/01 22:08:59', NULL, NULL);
INSERT INTO `process_task` (`process_task_id`, `process_node_key`, `process_node_name`, `process_id`, `process_template_key`, `process_task_actor`, `process_task_operation`, `process_task_form_url`, `process_bus_data_snapshot`, `process_task_opinion`, `process_task_node_type`, `process_task_status`, `process_task_create_time`, `process_task_close_time`, `process_task_remark`) VALUES ('86df81f0245a4824a10bffe884939f2f', 'start', '网络策略申请开始节点', '70c4cfe0913048dabaad5671182295da', 'wlclsq', '超级管理员', '超级管理员', '', NULL, '', 'start', 'treated', '2022/03/01 22:27:36', '2022/03/01 22:27:36', '流程引擎跳过开始节点');
INSERT INTO `process_task` (`process_task_id`, `process_node_key`, `process_node_name`, `process_id`, `process_template_key`, `process_task_actor`, `process_task_operation`, `process_task_form_url`, `process_bus_data_snapshot`, `process_task_opinion`, `process_task_node_type`, `process_task_status`, `process_task_create_time`, `process_task_close_time`, `process_task_remark`) VALUES ('8982e5f903c843f5ac40dddb03057ec2', 'wlclsq_dsjjsh', '网络策略申请_大数据审核', '70c4cfe0913048dabaad5671182295da', 'wlclsq', 'dsjj', '超级管理员', NULL, NULL, NULL, 'branch_task', 'cancel', '2022/03/01 22:28:20', NULL, NULL);
INSERT INTO `process_task` (`process_task_id`, `process_node_key`, `process_node_name`, `process_id`, `process_template_key`, `process_task_actor`, `process_task_operation`, `process_task_form_url`, `process_bus_data_snapshot`, `process_task_opinion`, `process_task_node_type`, `process_task_status`, `process_task_create_time`, `process_task_close_time`, `process_task_remark`) VALUES ('8cc6d6ca21d0495799feac55b56c448d', 'wlclsq_dsjjsh', '网络策略申请_大数据审核', 'fb1c5f32b4794d8aa93a29e2418947f5', 'wlclsq', 'dsjj', '超级管理员', NULL, NULL, NULL, 'branch_task', 'cancel', '2022/03/01 22:45:54', NULL, NULL);
INSERT INTO `process_task` (`process_task_id`, `process_node_key`, `process_node_name`, `process_id`, `process_template_key`, `process_task_actor`, `process_task_operation`, `process_task_form_url`, `process_bus_data_snapshot`, `process_task_opinion`, `process_task_node_type`, `process_task_status`, `process_task_create_time`, `process_task_close_time`, `process_task_remark`) VALUES ('95ec996d32e74a1093734cf80997d0ee', 'wlclsq_tjsq', '网络策略申请_厅局申请', 'fb1c5f32b4794d8aa93a29e2418947f5', 'wlclsq', 'linyeju', '超级管理员', NULL, NULL, NULL, 'task', 'cancel', '2022/03/01 22:36:21', NULL, NULL);
INSERT INTO `process_task` (`process_task_id`, `process_node_key`, `process_node_name`, `process_id`, `process_template_key`, `process_task_actor`, `process_task_operation`, `process_task_form_url`, `process_bus_data_snapshot`, `process_task_opinion`, `process_task_node_type`, `process_task_status`, `process_task_create_time`, `process_task_close_time`, `process_task_remark`) VALUES ('a58f20eabdf741dc9af7822f3318d843', 'wlclsq_zssh', '网络策略申请_正数审核', 'fb1c5f32b4794d8aa93a29e2418947f5', 'wlclsq', 'zhsangsan', '超级管理员', NULL, NULL, NULL, 'branch_task', 'cancel', '2022/03/01 22:37:10', NULL, NULL);
INSERT INTO `process_task` (`process_task_id`, `process_node_key`, `process_node_name`, `process_id`, `process_template_key`, `process_task_actor`, `process_task_operation`, `process_task_form_url`, `process_bus_data_snapshot`, `process_task_opinion`, `process_task_node_type`, `process_task_status`, `process_task_create_time`, `process_task_close_time`, `process_task_remark`) VALUES ('a5a25dcf6a8d4f6da8f962a98c1d0c8a', '', '网络策略申请_厅局申请', 'b4e40b4e543f43a39c5241b34f2c5a19', 'wlclsq', 'shuiliju', 'jimisun', NULL, NULL, '意见', 'task', 'treated', '2022/03/01 22:03:32', '2022/03/01 22:04:23', NULL);
INSERT INTO `process_task` (`process_task_id`, `process_node_key`, `process_node_name`, `process_id`, `process_template_key`, `process_task_actor`, `process_task_operation`, `process_task_form_url`, `process_bus_data_snapshot`, `process_task_opinion`, `process_task_node_type`, `process_task_status`, `process_task_create_time`, `process_task_close_time`, `process_task_remark`) VALUES ('a93cb454d19e46de967919f18e6e56ed', 'wlclsq_tjsq', '网络策略申请_厅局申请', 'd6dba4914e0e494281db6dd35e22208c', 'wlclsq', 'linyeju', 'jimisun', NULL, NULL, '意见', 'task', 'treated', '2022/03/01 22:08:43', '2022/03/01 22:08:59', NULL);
INSERT INTO `process_task` (`process_task_id`, `process_node_key`, `process_node_name`, `process_id`, `process_template_key`, `process_task_actor`, `process_task_operation`, `process_task_form_url`, `process_bus_data_snapshot`, `process_task_opinion`, `process_task_node_type`, `process_task_status`, `process_task_create_time`, `process_task_close_time`, `process_task_remark`) VALUES ('aa65469821db4c078afa522d5fa02b4f', 'wlclsq_tjsq', '网络策略申请_厅局申请', 'b4e40b4e543f43a39c5241b34f2c5a19', 'wlclsq', 'linyeju', 'jimisun', NULL, NULL, '意见', 'task', 'treated', '2022/03/01 22:03:32', '2022/03/01 22:04:54', NULL);
INSERT INTO `process_task` (`process_task_id`, `process_node_key`, `process_node_name`, `process_id`, `process_template_key`, `process_task_actor`, `process_task_operation`, `process_task_form_url`, `process_bus_data_snapshot`, `process_task_opinion`, `process_task_node_type`, `process_task_status`, `process_task_create_time`, `process_task_close_time`, `process_task_remark`) VALUES ('ac93b16ba9e1416496fe9e0f428e0bed', 'wlclsq_zssh', '网络策略申请_正数审核', 'fb1c5f32b4794d8aa93a29e2418947f5', 'wlclsq', 'zhsangsan', '超级管理员', NULL, NULL, NULL, 'branch_task', 'cancel', '2022/03/01 22:46:37', NULL, NULL);
INSERT INTO `process_task` (`process_task_id`, `process_node_key`, `process_node_name`, `process_id`, `process_template_key`, `process_task_actor`, `process_task_operation`, `process_task_form_url`, `process_bus_data_snapshot`, `process_task_opinion`, `process_task_node_type`, `process_task_status`, `process_task_create_time`, `process_task_close_time`, `process_task_remark`) VALUES ('af6aed322c034350bd8cc7d056745461', 'wlclsq_end', '网络策略申请_结束节点', 'b4e40b4e543f43a39c5241b34f2c5a19', 'wlclsq', '超级管理员', '超级管理员', '', NULL, '', 'end', 'treated', '2022/03/01 22:06:46', '2022/03/01 22:06:46', '流程引擎自动执行结束节点');
INSERT INTO `process_task` (`process_task_id`, `process_node_key`, `process_node_name`, `process_id`, `process_template_key`, `process_task_actor`, `process_task_operation`, `process_task_form_url`, `process_bus_data_snapshot`, `process_task_opinion`, `process_task_node_type`, `process_task_status`, `process_task_create_time`, `process_task_close_time`, `process_task_remark`) VALUES ('b5892aef82184d56aace0a9a862d17bf', 'wlclsq_tjsq', '网络策略申请_厅局申请', 'd6dba4914e0e494281db6dd35e22208c', 'wlclsq', 'shuiliju', '超级管理员', NULL, NULL, NULL, 'task', 'cancel', '2022/03/01 22:08:43', NULL, NULL);
INSERT INTO `process_task` (`process_task_id`, `process_node_key`, `process_node_name`, `process_id`, `process_template_key`, `process_task_actor`, `process_task_operation`, `process_task_form_url`, `process_bus_data_snapshot`, `process_task_opinion`, `process_task_node_type`, `process_task_status`, `process_task_create_time`, `process_task_close_time`, `process_task_remark`) VALUES ('bfb1d4928b2048caa3c827d7cb01feb1', 'wlclsq_end', '网络策略申请_结束节点', 'd6dba4914e0e494281db6dd35e22208c', 'wlclsq', '超级管理员', '超级管理员', '', NULL, '', 'end', 'treated', '2022/03/01 22:10:24', '2022/03/01 22:10:24', '流程引擎自动执行结束节点');
INSERT INTO `process_task` (`process_task_id`, `process_node_key`, `process_node_name`, `process_id`, `process_template_key`, `process_task_actor`, `process_task_operation`, `process_task_form_url`, `process_bus_data_snapshot`, `process_task_opinion`, `process_task_node_type`, `process_task_status`, `process_task_create_time`, `process_task_close_time`, `process_task_remark`) VALUES ('c1ddf61208af4fc1923a72a8941cc50c', 'wlclsq_yyscl', '网络策略申请_运营商处理', 'd6dba4914e0e494281db6dd35e22208c', 'wlclsq', 'zhongyuanyun', 'jimisun', NULL, NULL, '意见', 'branch_task', 'treated', '2022/03/01 22:09:00', '2022/03/01 22:10:22', NULL);
INSERT INTO `process_task` (`process_task_id`, `process_node_key`, `process_node_name`, `process_id`, `process_template_key`, `process_task_actor`, `process_task_operation`, `process_task_form_url`, `process_bus_data_snapshot`, `process_task_opinion`, `process_task_node_type`, `process_task_status`, `process_task_create_time`, `process_task_close_time`, `process_task_remark`) VALUES ('c24c4e62d3dd4a16ab6199226db8a0c8', 'wlclsq_tjsq', '网络策略申请_厅局申请', '70c4cfe0913048dabaad5671182295da', 'wlclsq', 'shuiliju', 'jimisun', NULL, NULL, '意见', 'task', 'treated', '2022/03/01 22:27:37', '2022/03/01 22:28:19', NULL);
INSERT INTO `process_task` (`process_task_id`, `process_node_key`, `process_node_name`, `process_id`, `process_template_key`, `process_task_actor`, `process_task_operation`, `process_task_form_url`, `process_bus_data_snapshot`, `process_task_opinion`, `process_task_node_type`, `process_task_status`, `process_task_create_time`, `process_task_close_time`, `process_task_remark`) VALUES ('c8e5f335a054403aab45dcd6cad39404', 'wlclsq_hzsjjg', '网络策略申请_汇总数据结果', 'd6dba4914e0e494281db6dd35e22208c', 'wlclsq', '超级管理员', '超级管理员', '', NULL, '', 'close_gateway', 'treated', '2022/03/01 22:10:23', '2022/03/01 22:10:23', '流程引擎跳过结束网关');
INSERT INTO `process_task` (`process_task_id`, `process_node_key`, `process_node_name`, `process_id`, `process_template_key`, `process_task_actor`, `process_task_operation`, `process_task_form_url`, `process_bus_data_snapshot`, `process_task_opinion`, `process_task_node_type`, `process_task_status`, `process_task_create_time`, `process_task_close_time`, `process_task_remark`) VALUES ('c90d5c72d98e4d31bdc711ab61a15654', 'wlclsq_dsjjsh', '网络策略申请_大数据审核', 'fb1c5f32b4794d8aa93a29e2418947f5', 'wlclsq', 'dsjj', '超级管理员', NULL, NULL, NULL, 'branch_task', 'cancel', '2022/03/01 22:36:47', NULL, NULL);
INSERT INTO `process_task` (`process_task_id`, `process_node_key`, `process_node_name`, `process_id`, `process_template_key`, `process_task_actor`, `process_task_operation`, `process_task_form_url`, `process_bus_data_snapshot`, `process_task_opinion`, `process_task_node_type`, `process_task_status`, `process_task_create_time`, `process_task_close_time`, `process_task_remark`) VALUES ('cb911f9f508d46ef908184a09f993549', 'wlclsq_zssh', '网络策略申请_正数审核', 'b4e40b4e543f43a39c5241b34f2c5a19', 'wlclsq', 'zhsangsan', 'jimisun', NULL, NULL, '意见', 'branch_task', 'treated', '2022/03/01 22:06:07', '2022/03/01 22:06:45', NULL);
INSERT INTO `process_task` (`process_task_id`, `process_node_key`, `process_node_name`, `process_id`, `process_template_key`, `process_task_actor`, `process_task_operation`, `process_task_form_url`, `process_bus_data_snapshot`, `process_task_opinion`, `process_task_node_type`, `process_task_status`, `process_task_create_time`, `process_task_close_time`, `process_task_remark`) VALUES ('cee1a28422ef46c8a8f85b5fc124d4d6', 'wlclsq_zssh', '网络策略申请_正数审核', '8cdef1c18bf842799be7b266597d7ca0', 'wlclsq', 'dsjj', 'jimisun', NULL, NULL, '意见', 'branch_task', 'treated', '2022/03/01 21:45:39', '2022/03/01 21:58:40', NULL);
INSERT INTO `process_task` (`process_task_id`, `process_node_key`, `process_node_name`, `process_id`, `process_template_key`, `process_task_actor`, `process_task_operation`, `process_task_form_url`, `process_bus_data_snapshot`, `process_task_opinion`, `process_task_node_type`, `process_task_status`, `process_task_create_time`, `process_task_close_time`, `process_task_remark`) VALUES ('cf021be5f39445448fc8b85a284de5c3', 'wlclsq_zssh', '网络策略申请_正数审核', '70c4cfe0913048dabaad5671182295da', 'wlclsq', 'zhsangsan', '超级管理员', NULL, NULL, NULL, 'branch_task', 'cancel', '2022/03/01 22:31:45', NULL, NULL);
INSERT INTO `process_task` (`process_task_id`, `process_node_key`, `process_node_name`, `process_id`, `process_template_key`, `process_task_actor`, `process_task_operation`, `process_task_form_url`, `process_bus_data_snapshot`, `process_task_opinion`, `process_task_node_type`, `process_task_status`, `process_task_create_time`, `process_task_close_time`, `process_task_remark`) VALUES ('d4dd905b88974f1da3f4bc5aa6cc00ca', 'wlclsq_yyscl', '网络策略申请_运营商处理', '70c4cfe0913048dabaad5671182295da', 'wlclsq', 'laintong', '超级管理员', NULL, NULL, NULL, 'branch_task', 'cancel', '2022/03/01 22:28:20', NULL, NULL);
INSERT INTO `process_task` (`process_task_id`, `process_node_key`, `process_node_name`, `process_id`, `process_template_key`, `process_task_actor`, `process_task_operation`, `process_task_form_url`, `process_bus_data_snapshot`, `process_task_opinion`, `process_task_node_type`, `process_task_status`, `process_task_create_time`, `process_task_close_time`, `process_task_remark`) VALUES ('d7725bac185f46a1a348f46a8ebcd220', 'wlclsq_end', '网络策略申请_结束节点', '70c4cfe0913048dabaad5671182295da', 'wlclsq', '超级管理员', '超级管理员', '', NULL, '', 'end', 'treated', '2022/03/01 22:32:48', '2022/03/01 22:32:48', '流程引擎自动执行结束节点');
INSERT INTO `process_task` (`process_task_id`, `process_node_key`, `process_node_name`, `process_id`, `process_template_key`, `process_task_actor`, `process_task_operation`, `process_task_form_url`, `process_bus_data_snapshot`, `process_task_opinion`, `process_task_node_type`, `process_task_status`, `process_task_create_time`, `process_task_close_time`, `process_task_remark`) VALUES ('e1fb8177394a4d0d9fc163346b402c13', 'wlclsq_end', '网络策略申请_结束节点', '8cdef1c18bf842799be7b266597d7ca0', 'wlclsq', '超级管理员', '超级管理员', '', NULL, '', 'end', 'treated', '2022/03/01 21:58:51', '2022/03/01 21:58:51', '流程引擎自动执行结束节点');
INSERT INTO `process_task` (`process_task_id`, `process_node_key`, `process_node_name`, `process_id`, `process_template_key`, `process_task_actor`, `process_task_operation`, `process_task_form_url`, `process_bus_data_snapshot`, `process_task_opinion`, `process_task_node_type`, `process_task_status`, `process_task_create_time`, `process_task_close_time`, `process_task_remark`) VALUES ('e464c1e26f7842989130c1cf7aa84c55', 'wlclsq_zssh', '网络策略申请_正数审核', 'fb1c5f32b4794d8aa93a29e2418947f5', 'wlclsq', 'dsjj', 'jimisun', NULL, NULL, '这是一个意见', 'branch_task', 'rejected', '2022/03/01 22:37:09', '2022/03/01 22:45:26', NULL);
INSERT INTO `process_task` (`process_task_id`, `process_node_key`, `process_node_name`, `process_id`, `process_template_key`, `process_task_actor`, `process_task_operation`, `process_task_form_url`, `process_bus_data_snapshot`, `process_task_opinion`, `process_task_node_type`, `process_task_status`, `process_task_create_time`, `process_task_close_time`, `process_task_remark`) VALUES ('e97116467206493e89a454f3dda79ebc', 'wlclsq_dsjjsh', '网络策略申请_大数据审核', 'b4e40b4e543f43a39c5241b34f2c5a19', 'wlclsq', 'dsjzx', 'jimisun', NULL, NULL, '意见', 'branch_task', 'treated', '2022/03/01 22:04:56', '2022/03/01 22:06:06', NULL);
INSERT INTO `process_task` (`process_task_id`, `process_node_key`, `process_node_name`, `process_id`, `process_template_key`, `process_task_actor`, `process_task_operation`, `process_task_form_url`, `process_bus_data_snapshot`, `process_task_opinion`, `process_task_node_type`, `process_task_status`, `process_task_create_time`, `process_task_close_time`, `process_task_remark`) VALUES ('f8ff7bd3bee54c64a5a02ee9756cd740', 'wlclsq_yyscl', '网络策略申请_运营商处理', 'd6dba4914e0e494281db6dd35e22208c', 'wlclsq', 'laintong', '超级管理员', NULL, NULL, NULL, 'branch_task', 'cancel', '2022/03/01 22:09:00', NULL, NULL);
COMMIT;

-- ----------------------------
-- Table structure for process_template
-- ----------------------------
DROP TABLE IF EXISTS `process_template`;
CREATE TABLE `process_template` (
  `process_template_key` varchar(255) COLLATE utf8mb4_bin NOT NULL COMMENT '流程模板KEY',
  `process_template_name` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '流程模板名称',
  `process_template_status` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '流程模板状态',
  `process_template_node_define` longtext COLLATE utf8mb4_bin COMMENT '流程模板定义',
  PRIMARY KEY (`process_template_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

-- ----------------------------
-- Records of process_template
-- ----------------------------
BEGIN;
INSERT INTO `process_template` (`process_template_key`, `process_template_name`, `process_template_status`, `process_template_node_define`) VALUES ('wlclsq', '网络策略申请', 'open', '[{\n    \"node_type\":\"start\",\n    \"node_key\" :\"start\",\n    \"node_name\" : \"网络策略申请开始节点\",\n    \"next_node_key\" : \"wlclsq_tjsq\",\n    \"next_node_name\" : \"网络策略申请_厅局申请\"\n    },{\n    \"node_type\":\"task\",\n    \"node_key\" :\"wlclsq_tjsq\",\n    \"node_name\" : \"网络策略申请_厅局申请\",\n    \"node_distribute_type\":\"group\",\n    \"node_task_execute_type\":\"any\",\n    \"node_actors\":\"linyeju,shuiliju\",\n    \"next_node_key\" : \"wlclsq_sqcl_open_getway\",\n    \"next_node_name\" : \"网络策略申请_判断厅局申请材料是否包含59地址\"\n  },{\n    \"node_type\":\"open_gateway\",\n    \"node_key\" :\"wlclsq_sqcl_open_getway\",\n    \"node_name\" : \"网络策略申请_判断厅局申请材料是否包含59地址\",\n    \"open_gateway_script\":\"wlclsq_dsjjsh,wlclsq_yyscl\"\n  },{\n    \"node_type\":\"branch_task\",\n    \"node_key\" :\"wlclsq_dsjjsh\",\n    \"node_name\" : \"网络策略申请_大数据审核\",\n    \"node_distribute_type\":\"group\",\n    \"node_task_execute_type\":\"any\",\n    \"node_actors\":\"dsjj,dsjzx\",\n    \"next_node_key\" : \"wlclsq_zssh\",\n    \"next_node_name\" : \"网络策略申请_正数审核\"\n  },{\n    \"node_type\":\"branch_task\",\n    \"node_key\" :\"wlclsq_zssh\",\n    \"node_name\" : \"网络策略申请_正数审核\",\n    \"node_distribute_type\":\"group\",\n    \"node_task_execute_type\":\"any\",\n    \"node_actors\":\"dsjj,zhsangsan\",\n    \"next_node_key\" : \"wlclsq_hzsjjg\",\n    \"next_node_name\" : \"网络策略申请_汇总数据结果\"\n  },{\n    \"node_type\":\"branch_task\",\n    \"node_key\" :\"wlclsq_yyscl\",\n    \"node_name\" : \"网络策略申请_运营商处理\",\n    \"node_distribute_type\":\"group\",\n    \"node_task_execute_type\":\"any\",\n    \"node_actors\":\"zhongyuanyun,laintong\",\n    \"next_node_key\" : \"wlclsq_hzsjjg\",\n    \"next_node_name\" : \"网络策略申请_汇总数据结果\"\n  },{\n    \"node_type\":\"close_gateway\",\n    \"node_key\" :\"wlclsq_hzsjjg\",\n    \"node_name\" : \"网络策略申请_汇总数据结果\",\n    \"next_node_key\" : \"wlclsq_end\",\n    \"next_node_name\" : \"网络策略申请_结束节点\"\n  },{\n    \"node_type\":\"end\",\n    \"node_key\" :\"wlclsq_end\",\n    \"node_name\" : \"网络策略申请_结束节点\"\n    }]');
COMMIT;

SET FOREIGN_KEY_CHECKS = 1;
